### ISSUE TITLE
Class parameters for final row is not in YAML format

### ISSUE THREAD

**Issue by FreddyFox** [Kolkman/OpenHab-Various#1]
First of all, great work! I really like your widget a lot.

One issue I came across while testing it out was that the class parameters for the last row in the widget is not applied since they are listed in one row and don't conform to YAML formating.

This causes problems when using the widget in Popup/Popover mode and also some width issues on mobile platforms. Fixing this made everything look a lot nicer in the above mentioned use cases!

I should have pulled the repo and made a merge request but I think it might be just as easy just marking the line and you can update it in the master branch if you want to.

https://github.com/Kolkman/OpenHab-Various/blob/4e31820dfc0e20bbefca69deed0eea33b1633d87/OH3%20Widgets/Spotify%20Widget/Spotify-Widget.yaml#L255

**Comment by Kolkman** [comment]
Thanks FreddyFox,

I am not using OpenHAb any longer, and forgot the details of this code and can’t test.

Please send me a ‘diff -u' so I  am sure that I am fixing the right thing.



—Olaf

**Comment by FreddyFox** [comment]
May I ask out of curiosity if you are still into home automation, and if so, what platform are you now using and why not OH3? An open ended question so feel free to keep it short :)

See below for diff -u

```diff --git a/OH3 Widgets/Spotify Widget/Spotify-Widget.yaml b/OH3 Widgets/Spotify Widget/Spotify-Widget.yaml
index ca61c35..99855f9 100644
--- a/OH3 Widgets/Spotify Widget/Spotify-Widget.yaml    
+++ b/OH3 Widgets/Spotify Widget/Spotify-Widget.yaml    
@@ -252,7 +252,10 @@ slots:
                     item: =props.prefix+"_Volume"
     - component: f7-row
       config:
-        class: -justify-content-space-around -align-items-center -align-content-stretch
+        class: 
+          - justify-content-space-around
+          - align-items-center
+          - align-content-stretch
         style:
           position: relative
           top: -20px```

**Comment by Kolkman** [comment]
I've applied the fix, thanks for reporting and the patch.

On HomeAutomation.

My interest got sparked because of zigbee based light controls (dimmers mainly) but spun a bit out of control.

I started with OpenHab but discovered that some integrations I wanted to use where either not available (could be I didn't search well enough) or not really satisfactory.  Making your own plug-ins is fun, but also time consuming, and while playing around with HomeAssistant I simply experienced less friction.

Anyhow, I am now using HomeAssistant, Zigbee2MQTT, Appdaemon as containers on a reasonably powered headless NUC. Which hosts a bunch of other containers too like Influx2/Grafana for graphing, an Emby server for media, etc.

HomeAssistant had a bunch of interfaces relatively easily available like an integration to interface with the amplifier, solar panels, dishwasher, car, my modem - all without little hassle.

Finally I like the HomeAssisitant interface, relatively easy to configure and some control over who gets to see what menu.

Hope this is informative.
